
### Create new order
POST http://localhost:30440/api/orders
Content-Type: application/json

{
    "items": 
    [
        {
        # "productId": 1000, # this id dont exist and will throw a concatenation error
        "productId": 2,
        "price": 50,
        "quantity": 2
        },
        {
            "productId": 1,
            "price": 50,
            "quantity": 2
        }
    ]
}

### Get order by ID
GET http://localhost:30440/api/orders/f2455ff5-a1cc-4f41-a38d-dc363b25ebfd
Content-Type: application/json

### Get all orders
GET http://localhost:30440/api/orders?limit=10&offset=0
Content-Type: application/json

### Update order by ID
PATCH http://localhost:3000/api/orders/bbe8e8dc-14e1-4f88-a26a-32ceaa3f74a1
Content-Type: application/json

{
    "status": "CANCELLED"
}


